apiVersion: v1
kind: Service
metadata:
  name: node-cast-service
spec:
  selector:
    app: node-cast
    version: blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer
