name: CI Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: '**'

permissions:
  actions: read
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: node:18-buster-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn

  unit-test:
    runs-on: ubuntu-latest
    container:
      image: node:18-buster-slim
    needs: install
    strategy:
      matrix:
        command: [client, node-cast]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn

      - name: Check ${{ matrix.command }} lint
        run: yarn nx test ${{ matrix.command}}
