name: CI Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: '**'

permissions:
  actions: read
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: node:18-buster-slim
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES.POSTGRES_PASSWORD }}
        # options: >-
        #   # --health-cmd="pg_isready -U ${{ secrets.POSTGRES.POSTGRES_USER }}"
        #   --health-interval=10s
        #   --health-timeout=5s
        #   --health-retries=5
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=15s
          --health-timeout=10s
          --health-retries=10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn

      - name: Ensure npm cache directory exists
        run: mkdir -p ~/.npm

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # - name: Wait for PostgreSQL to be ready
      #   run: |
      #     until pg_isready -h localhost -p 5432 -U ${{ secrets.POSTGRES.POSTGRES_USER }}; do
      #       echo "Waiting for PostgreSQL to be ready..."
      #       sleep 1
      #     done

      - name: Wait for Redis to be ready
        run: |
          until redis-cli -h localhost -p 6379 ping | grep PONG; do
            echo "Waiting for Redis to be ready..."
            sleep 1
          done

  unit-test:
    runs-on: ubuntu-latest
    container:
      image: node:18-buster-slim
    needs: install
    strategy:
      matrix:
        command: [client, node-cast]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn

      - name: Ensure npm cache directory exists
        run: mkdir -p ~/.npm

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Check ${{ matrix.command }} lint
        run: yarn nx test ${{ matrix.command}}
