name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

test-backend:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        command: [test, e2e]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Backend Tests
        run: nx ${{ matrix.command }} node-cast-${{ matrix.command }}

  test-frontend:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        command: [test, e2e]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Frontend Tests
        run: nx ${{ matrix.command }} client-${{ matrix.command }}
